#!/bin/bash

packages=(
    github.com/cloudfoundry/loggregatorlib/agentlistener
    github.com/cloudfoundry/loggregatorlib/cfcomponent
    github.com/cloudfoundry/loggregatorlib/emitter
    github.com/cloudfoundry/loggregatorlib/loggregatorclient
    github.com/cloudfoundry/loggregatorlib/logmessage
    github.com/cloudfoundry/loggregatorlib/appid
)

for package in "${packages[@]}"
do
    go list -f '{{range .TestImports}}{{.}}
      {{end}}' $package | xargs go get -v
done

